baseurl         = "/"
theme           = "casper"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Grupo Guía y Scout Hispano Americano"
  subtitle    = "Desde 1957"

  cover       = "img/grupo1.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "GuiasyScoutsCha"
  fbName = "scoutscha"
  instagramName = "scouts_hispano"

  logo = "logo-grupo-gris.png"
  orgName = "Grupo Guía y Scout Hispano Americano"
  orgWebsite = "https://www.scoutshispano.cl"
  orgDescription = "El mejor grupo scout de Chile"
  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Manadas"
  url = "/tags/manada/"
  weight = 100

[[menu.main]]
  name = "Compañía"
  url = "/tags/cia/"
  weight = 99

[[menu.main]]
  name = "Tropa"
  url = "/tags/tropa/"
  weight = 98

[[menu.main]]
  name = "Ruta"
  url = "/tags/ruta/"
  weight = 97

  [[menu.main]]
  name = "Inscríbete"
  url = "https://goo.gl/forms/0NBCtTDmjrc84a0J3"
  weight = 5

